USE QUANLYSINHVIEN;

SELECT*FROM CLASS;
SELECT*FROM MARK;
SELECT*FROM STUDENT;
SELECT*FROM SUBJECT_SCHOOL;

SELECT Address,COUNT(StudentID) AS QUANTITY FROM STUDENT GROUP BY Address;

SELECT S.StudentID,S.StudentName,AVG(M.Mark) AS 'AVG' 
FROM STUDENT S JOIN MARK M ON S.StudentID = M.StudentID
GROUP BY S.StudentID,S.StudentName;

SELECT S.StudentID,S.StudentName,AVG(M.Mark) AS 'AVG' 
FROM STUDENT S JOIN MARK M ON S.StudentID = M.StudentID
GROUP BY S.StudentID,S.StudentName
HAVING AVG(M.Mark)>15;

SELECT S.StudentID,S.StudentName,AVG(M.Mark) AS 'AVG' 
FROM STUDENT S JOIN MARK M ON S.StudentID = M.StudentID
GROUP BY S.StudentID,S.StudentName
HAVING AVG(M.Mark) >= ALL (SELECT AVG(Mark) FROM MARK GROUP BY StudentID);
