USE QUANLYSINHVIEN;

SELECT*FROM CLASS;
SELECT*FROM MARK;
SELECT*FROM STUDENT;
SELECT*FROM SUBJECT_SCHOOL;

SELECT MAX(Credit)
FROM SUBJECT_SCHOOL;

SELECT MAX(Mark)
FROM MARK;

SELECT S.StudentName,AVG(M.Mark)
FROM STUDENT S JOIN MARK M ON S.StudentID = M.StudentID
GROUP BY S.StudentID
ORDER BY AVG(M.Mark) DESC;